// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbkxxceolvvyxzgykhcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZia3h4Y2VvbHZ2eXh6Z3lraGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzUwMTAsImV4cCI6MjA1OTk1MTAxMH0.jChrmBa7hDS9GVSmjOqVw6NmvbDa6QMj4jOfukjkr0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);